import '@client/styles/tailwind.css';

import type { Metadata } from 'next';
import { Header } from './header';
import { Nav } from './nav';
import { getEnv } from '@common/env';

export const metadata: Metadata = {
  title: 'NextJS Starter',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const GA_MEASUREMENT_ID = getEnv('GA_MEASUREMENT_ID', '');
  return (
    <html lang='en'>
      <head>
        <link rel='stylesheet' href='https://rsms.me/inter/inter.css' />
        {GA_MEASUREMENT_ID && (
          <>
            <script
              async
              src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
            ></script>
            <script>
              {`window.dataLayer = window.dataLayer || [];
          function gtag() {
            window.dataLayer.push(arguments)
          }
          function gevt(evt, params) {
            gtag('event', evt, params)
          }
          gtag('js', new Date());
          gtag('config', '${GA_MEASUREMENT_ID}');`}
            </script>
          </>
        )}
      </head>

      <body className='mb-[56px]  dark:bg-slate-900 sm:mb-[116px]'>
        <Header />
        <div className='mx-auto flex h-[calc(100vh-70px)] max-w-[90rem]'>
          <div className='-my-8 h-full space-y-8 overflow-y-auto overflow-x-hidden px-8 pb-10 pt-7 lg:my-0'>
            <Nav />
          </div>
          <div className='flex-1 overflow-y-auto overflow-x-hidden px-4 pt-8 sm:px-6 md:px-8'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
