import '@client/styles/tailwind.css';

import type { Metadata } from 'next';
import { ToastContainerWrapper } from './toast';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <link rel='stylesheet' href='https://rsms.me/inter/inter.css' />
      </head>
      <body>
        <ToastContainerWrapper />
        {children}
      </body>
    </html>
  );
}
